namespace NumberSorter.Core.Logic
{
    public enum AlgorhythmType
    {
        CombSort,
        HeapSort,
        CycleSort,
        GnomeSort,
        BinarySort,
        BubbleSort,
        OddEvenSort,
        SelectionSort,
        InsertionSort,
        DequeMergeSort,
        WindowMergeSort,
        CocktailShakerSort,
        RecursiveMergeSort,
        DoubleSelectionSort,
        WindowWindowTimSort,
        HalfInPlaceMergeSort,
        QuickSortRandomPivot,
        KindaInPlaceMergeSort,
        TripleWindowMergeSort,
        InsertionWindowTimSort,
        QuickSortMedianOfThree,
        WorkAreaInPlaceMergeSort,
        GallopingRecursiveMergeSort,
        InsertionTripleWindowTimSort,
        TripleWindowTripleWindowTimSort,
        QuickSortRandomPivotCutoffWindow,
        QuickSortRandomPivotCutoffInsertion,
        QuickSortRandomPivotCutoffTripleWindow,
    }
}
