namespace NumberSorter.Core.Logic
{
    public enum AlgorhythmType
    {
        CombSort,
        HeapSort,
        CycleSort,
        GnomeSort,
        BinarySort,
        BubbleSort,
        CircleSort,
        PancakeSort,
        OddEvenSort,
        SelectionSort,
        InsertionSort,
        DequeMergeSort,
        ShellSortCiura,
        ShellSortKnuth,
        ShellSortTokuda,
        WindowMergeSort,
        CocktailShakerSort,
        RecursiveMergeSort,
        DoubleSelectionSort,
        WindowWindowTimSort,
        HalfInPlaceMergeSort,
        KindaInPlaceMergeSort,
        TripleWindowMergeSort,
        InsertionWindowTimSort,
        WorkAreaInPlaceMergeSort,
        GallopingRecursiveMergeSort,
        InsertionTripleWindowTimSort,
        TripleWindowTripleWindowTimSort,

        GroupMultiMergeSort,
        SimpleMultiMergeSort,
        RecursiveGroupMultiMergeSort,
        RecursiveSimpleMultiMergeSort,

        QuickSortRandomPivot,
        QuickSortMedianOfThree,
        QuickSortRandomPivotCutoffWindow,
        QuickSortRandomPivotCutoffInsertion,
        QuickSortRandomPivotCutoffTripleWindow,
    }
}
